spring:
  datasource:
    url: jdbc:h2:mem:db
    username: user
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  liquibase:
    change-log: classpath:/liquibase/master.xml
